name: glucose_genie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - seaborn
  - pytorch
  - optuna
  - numpy<2.0.0
  - tensorboard
  - pip:
    - fastapi
    - uvicorn
    - thefuzz
    - pycomfort>=0.0.15
    - polars>=1.3.0
    - hybrid_search>=0.0.15
    - psutil #compartibilit
    - loguru
    - httpx
    - just-agents>=0.1.0
    - litellm>=1.42.5
    - FlagEmbedding
    - typer
    - darts==0.29.0
    - pmdarima==2.0.4
    - numpy==1.26.4
    - peft
